version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
jobs:

  terraform_plan:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      # If your terraform files are in a subdirectory, set TF_ROOT accordingly
      TF_ROOT: ./terraform # Update this!
    steps:
      - run:
          name: Skip if not pull request
          command: |
            if [ "$CIRCLE_PULL_REQUEST" == "" ]; then
              circleci step halt
            fi
      - checkout
      - run:
          name: Run terraform plan
          command: |
            # IMPORTANT: add any required steps here to setup cloud credentials so Terraform can run
            cd $TF_ROOT
            terraform init
            terraform plan -out tfplan.binary
            terraform show -json tfplan.binary > /tmp/plan.json
      - persist_to_workspace:
          root: /tmp
          paths:
            - plan.json
  infracost:
    working_directory: terraform
    docker:
      # Always use the latest 0.9.x version to pick up bug fixes and new resources.
      # See https://www.infracost.io/docs/integrations/cicd/#docker-images for other options
      - image: infracost/infracost:ci-0.9
    steps:
      - run:
          name: Skip if not pull request
          command: |
            if [ "$CIRCLE_PULL_REQUEST" == "" ]; then
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Run Infracost breakdown
          command: |
            # Generate Infracost JSON output, the following docs might be useful:
            # Multi-project/workspaces: https://www.infracost.io/docs/features/config_file
            # Combine Infracost JSON files: https://www.infracost.io/docs/features/cli_commands/#combined-output-formats
            infracost breakdown --path /tmp/plan.json --format json --out-file infracost.json
      - run:
          name: Run Infracost comment
          command: |
            # Extract the PR number from the PR URL
            PULL_REQUEST_NUMBER=${CIRCLE_PULL_REQUEST##*/}
            # See the 'Comment options' section in our README below for other options.
            infracost comment github --path infracost.json --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME --pull-request $PULL_REQUEST_NUMBER --github-token $GITHUB_TOKEN
  terraform_apply:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      # If your terraform files are in a subdirectory, set TF_ROOT accordingly
      TF_ROOT: ./terraform # Update this!
    steps:      
      - checkout
      - run:
          name: Run Terraform Apply 
          command: |
            cd $TF_ROOT
            terraform init
            terraform apply -auto-approve

workflows:
  infracost:
    jobs:
      - terraform_plan
      - infracost:
          requires:
            - terraform_plan
      - terraform_apply:
          filters:
            branches:
              only:
                - main